config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/dashboard", to: 'pages#dashboard'

  resources :booking_initial_data, only: :create
  resources :booking_dates, only: [:new, :create]
  resources :booking_categories, only: [:new, :create]
  resources :booking_options, only: [:new, :create]
  resources :booking_budgets, only: [:new, :create]

  resources :bookings, only: [:create, :show] do
    resources :booking_checkout, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    member do
      get :loading
    end
  end

  resources :events, only: [:show, :index] do
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-area-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="footer-icons">
            <ul>
              <li>
                <a href="#"><i class="fab fa-facebook-f"></i></a>
              </li>
              <li>
                <a href="#"><i class="fab fa-twitter"></i></a>
              </li>
              <li>
                <a href="#"><i class="fab fa-linkedin-in"></i></a>
              </li>
              <li>
                <a href="#"><i class="fab fa-github"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="credits">
            <a href="#">Privacy Policy</a> | <a href="#">Terms & Conditions</a>
          </div>
          <div class="copyright text-center">
            <p>
              &copy; Copyright 2020. | <strong><a href="#">Helio</a></strong> | All Rights Reserved.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<!--Navbar-->
<nav class="navbar">

  <!-- Navbar brand -->
  <%= link_to "helio", root_path, class: "navbar-brand" %>

  <!-- Collapse button -->
  <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
    aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="dark-blue-text"><i
        class="fas fa-bars"></i></span></button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent1">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <!-- Links -->

  </div>
  <!-- Collapsible content -->

</nav>
<!--/.Navbar-->

app/views/shared/_progressbar.html.erb
<div class="progressbar-wrapper">
  <div class="line">
  </div>
  <% [new_booking_date_path, new_booking_category_path, new_booking_option_path, new_booking_budget_path, new_booking_date_path ].each_with_index do |link, index| %>
    <% if step >= index + 1 %>
      <%= link_to index + 1, link, class: "pearl #{'active' if step == index + 1}" %>
    <% else %>
      <div class="pearl">
        <%= index + 1 %>
      </div>
    <% end %>
  <% end %>
</div>